# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "bump(go.mod): "
      prefix: "bump(go.mod)"
    labels:
      - "dependencies"
      - "go mod"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "bump(Dockerfile): "
      prefix: "bump(Dockerfile)"
    labels:
      - "dependencies"
      - "dockerfile"
     
     
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "bump(ci): "
      prefix: "bump(ci)"
    labels:
      - "dependencies"
      - "ci"

