# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "bump(go.mod): "
      prefix: "bump(go.mod)"
    labels:
      - "dependencies"
      - "go mod"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "bump(Dockerfile): "
      prefix: "bump(Dockerfile)"
    labels:
      - "dependencies"
      - "dockerfile"
     
     
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "bump(CI): "
      prefix: "bump(CI)"
    labels:
      - "dependencies"
      - "ci"

