version: "2"
run:
  build-tags:
    - integration
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - inamedparam
    - interfacebloat
    - ireturn
    - mnd
    - musttag
    - nakedret
    - nonamedreturns
    - paralleltest
    - perfsprint
    - recvcheck
    - revive
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - testifylint
    - embeddedstructfieldcheck
    - noinlineerr
    - funcorder
    - noctx


  settings:
    cyclop:
      max-complexity: 13
      package-average: 0
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: fmt\.Print.*
    funlen:
      lines: 69
      statements: 75
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - commentedOutCode
        - typeSwitchVar
        - whyNoLint
        - yodaStyleExpr
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 80
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
        ruleguard:
          rules: ""
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
        unnamedResult:
          checkExported: true
    gomoddirectives:
      replace-allow-list:
        - launchpad.net/gocheck
      replace-local: false
      exclude-forbidden: false
      retract-allow-no-explanation: false
    gosec:
      includes:
        - G401
        - G306
        - G101
      excludes:
        - G204
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: false
          pattern: (?i)example
          per_char_threshold: "3.0"
          truncate: "32"
        G306: "0600"
    govet:
      disable:
        - shadow
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 128
      tab-width: 1
    makezero:
      always: false
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 6
    nolintlint:
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    promlinter:
      strict: false
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: argument-limit
          arguments:
            - 4
          severity: warning
          disabled: true
        - name: atomic
          severity: warning
          disabled: false
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
            - "7"
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: true
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 7
          severity: warning
          disabled: true
        - name: confusing-naming
          severity: warning
          disabled: true
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: true
        - name: cyclomatic
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: true
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          severity: warning
          disabled: true
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: true
        - name: file-header
          arguments:
            - This is the text that must appear at the top of source files.
          severity: warning
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: function-result-limit
          arguments:
            - 2
          severity: warning
          disabled: true
        - name: function-length
          arguments:
            - 10
            - 0
          severity: warning
          disabled: true
        - name: get-return
          severity: warning
          disabled: true
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: true
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 80
          severity: warning
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: true
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: true
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: false
        - name: struct-tag
          severity: warning
          disabled: true
        - name: superfluous-else
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: var-naming
          arguments:
            - - ID
            - - VM
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: true
        - name: unexported-return
          severity: warning
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Printf
          severity: warning
          disabled: true
        - name: unnecessary-stmt
          severity: warning
          disabled: true
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          severity: warning
          disabled: true
        - name: unused-receiver
          severity: warning
          disabled: true
        - name: useless-break
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - 'all'
        - '-ST1000'
        - '-ST1003'
        - '-ST1016'
        - '-ST1017'
        - '-ST1020'
        - '-ST1021'
        - '-ST1022'
        - '-QF1008'
    tagalign:
      align: false
      sort: true
      order:
        - yaml
        - yml
        - json
        - toml
        - mapstructure
        - binding
        - validate
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
        use-field-name: false
    testifylint:
      enable-all: true
      disable:
        - require-error
    testpackage:
      skip-regexp: (export|internal)_test\.go
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: false
    whitespace:
      multi-if: false
      multi-func: false
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
      ignore-sig-regexps:
        - \.New.*Error\(
      ignore-package-globs:
        - context
        - encoding/*
        - github.com/pkg/*
        - github.com/helmwave/helmwave/*
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-assign-and-anything: false
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
      force-short-decl-cuddling: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - wrapcheck
        path: pkg/version/
      - linters:
          - lll
        path: config\.go
      - linters:
          - containedctx
          - dupl
          - dupword
          - forcetypeassert
          - funlen
          - goconst
          - godot
          - lll
          - revive
          - wrapcheck
        path: _test\.go
      - linters:
          - dupword
          - forbidigo
        path: cmd/
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
severity:
  default: error
  rules:
    - linters:
        - forcetypeassert
        - funlen
        - paralleltest
      severity: warning
    - linters:
        - godox
      severity: notice
formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
