version: 2

metadata:
  homepage: "https://helmwave.app/"
  maintainers:
    - "Dmitrii Zhiliaev"
    - "Sviatoslav Dumchenko"
  license: "MIT"
  description: "Helmwave is true release management for helm"

before:
  hooks:
    - go mod tidy

###
# Builds
###

builds:
  - &bin
    id: "helmwave"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goamd64:
      # Go can build using different instruction sets - https://github.com/golang/go/wiki/MinimumRequirements#amd64
      # We don't really need this type of optimization (limiting CPUs helmwave can run on) so we use general v1.
      - v1
      # - v2
      # - v3
      # - v4
    goos:
      - linux
      # - windows
      - darwin
    main: ./cmd/helmwave
    ldflags:
      - -s -w -X github.com/helmwave/helmwave/pkg/version.Version={{ .Version }}
  - <<: *bin
    main: ./cmd/schema
    id: schema
    binary: schema
  - <<: *bin
    main: ./cmd/gitops
    id: gitops
    binary: gitops

###
# Packages
###

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - homepage: https://helmwave.github.io/
    license: MIT
    maintainer: TBD
    formats:
      - apk
      - deb
      - rpm

checksum:
  name_template: "checksums.txt"

dockers:
  # helmwave
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/helmwave:{{ .Version }}-scratch-amd64
      - ghcr.io/helmwave/helmwave:scratch-amd64
      - diamon/helmwave:{{ .Version }}-scratch-amd64
      - diamon/helmwave:scratch-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Helmwave is true release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/helmwave"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/amd64"
      - "--target=scratch-goreleaser"
      - "--pull"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/helmwave:{{ .Version }}-scratch-arm64v8
      - ghcr.io/helmwave/helmwave:scratch-arm64v8
      - diamon/helmwave:{{ .Version }}-scratch-arm64v8
      - diamon/helmwave:scratch-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Helmwave is true release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/helmwave"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/arm64/v8"
      - "--target=scratch-goreleaser"
      - "--pull"
    goos: linux
    goarch: arm64
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/helmwave:{{ .Version }}-amd64
      - ghcr.io/helmwave/helmwave:latest-amd64
      - diamon/helmwave:{{ .Version }}-amd64
      - diamon/helmwave:latest-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Helmwave is true release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/helmwave"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
      - "--pull"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/helmwave:{{ .Version }}-arm64v8
      - ghcr.io/helmwave/helmwave:latest-arm64v8
      - diamon/helmwave:{{ .Version }}-arm64v8
      - diamon/helmwave:latest-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Helmwave is true release management for helm"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/helmwave"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/arm64/v8"
      - "--target=goreleaser"
      - "--pull"
    goos: linux
    goarch: arm64
    use: buildx

  # schema
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/schema:{{ .Version }}-scratch-amd64
      - ghcr.io/helmwave/schema:scratch-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Schema generator for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=schema"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/schema"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/amd64"
      - "--target=scratch-goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=schema"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/schema:{{ .Version }}-scratch-arm64v8
      - ghcr.io/helmwave/schema:scratch-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Schema generator for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=schema"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/schema"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/arm64/v8"
      - "--target=scratch-goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=schema"
    goos: linux
    goarch: arm64
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/schema:{{ .Version }}-amd64
      - ghcr.io/helmwave/schema:latest-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Schema generator for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=schema"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/schema"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=schema"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/schema:{{ .Version }}-arm64v8
      - ghcr.io/helmwave/schema:latest-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Schema generator for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=schema"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/schema"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/arm64/v8"
      - "--target=goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=schema"
    goos: linux
    goarch: arm64
    use: buildx

  # gitops
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/gitops:{{ .Version }}-scratch-amd64
      - ghcr.io/helmwave/gitops:scratch-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/amd64"
      - "--target=scratch-goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/gitops:{{ .Version }}-scratch-arm64v8
      - ghcr.io/helmwave/gitops:scratch-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/arm64/v8"
      - "--target=scratch-goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: arm64
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/gitops:{{ .Version }}-amd64
      - ghcr.io/helmwave/gitops:latest-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: amd64
    goamd64: v1
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - ghcr.io/helmwave/gitops:{{ .Version }}-arm64v8
      - ghcr.io/helmwave/gitops:latest-arm64v8
    build_flag_templates:
      - "--label=org.opencontainers.image.description=GitOps plugin for helmwave"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=gitops"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/gitops"
      - "--label=org.opencontainers.image.documentation=https://helmwave.app/"

      - "--platform=linux/arm64/v8"
      - "--target=goreleaser"
      - "--pull"
      - "--build-arg=PROJECT=gitops"
    goos: linux
    goarch: arm64
    use: buildx

docker_manifests:
  # helmwave: GitHub Container Registry
  - name_template: ghcr.io/helmwave/helmwave:{{ .Version }}-scratch
    image_templates:
      - ghcr.io/helmwave/helmwave:{{ .Version }}-scratch-amd64
      - ghcr.io/helmwave/helmwave:{{ .Version }}-scratch-arm64v8
  - name_template: ghcr.io/helmwave/helmwave:scratch
    image_templates:
      - ghcr.io/helmwave/helmwave:scratch-amd64
      - ghcr.io/helmwave/helmwave:scratch-arm64v8
  - name_template: ghcr.io/helmwave/helmwave:{{ .Version }}
    image_templates:
      - ghcr.io/helmwave/helmwave:{{ .Version }}-amd64
      - ghcr.io/helmwave/helmwave:{{ .Version }}-arm64v8
  - name_template: ghcr.io/helmwave/helmwave:latest
    image_templates:
      - ghcr.io/helmwave/helmwave:latest-amd64
      - ghcr.io/helmwave/helmwave:latest-arm64v8

  # schema: GitHub Container Registry
  - name_template: ghcr.io/helmwave/schema:{{ .Version }}-scratch
    image_templates:
      - ghcr.io/helmwave/schema:{{ .Version }}-scratch-amd64
      - ghcr.io/helmwave/schema:{{ .Version }}-scratch-arm64v8
  - name_template: ghcr.io/helmwave/schema:scratch
    image_templates:
      - ghcr.io/helmwave/schema:scratch-amd64
      - ghcr.io/helmwave/schema:scratch-arm64v8
  - name_template: ghcr.io/helmwave/schema:{{ .Version }}
    image_templates:
      - ghcr.io/helmwave/schema:{{ .Version }}-amd64
      - ghcr.io/helmwave/schema:{{ .Version }}-arm64v8
  - name_template: ghcr.io/helmwave/schema:latest
    image_templates:
      - ghcr.io/helmwave/schema:latest-amd64
      - ghcr.io/helmwave/schema:latest-arm64v8

  # gitops: GitHub Container Registry
  - name_template: ghcr.io/helmwave/gitops:{{ .Version }}-scratch
    image_templates:
      - ghcr.io/helmwave/gitops:{{ .Version }}-scratch-amd64
      - ghcr.io/helmwave/gitops:{{ .Version }}-scratch-arm64v8
  - name_template: ghcr.io/helmwave/gitops:scratch
    image_templates:
      - ghcr.io/helmwave/gitops:scratch-amd64
      - ghcr.io/helmwave/gitops:scratch-arm64v8
  - name_template: ghcr.io/helmwave/gitops:{{ .Version }}
    image_templates:
      - ghcr.io/helmwave/gitops:{{ .Version }}-amd64
      - ghcr.io/helmwave/gitops:{{ .Version }}-arm64v8
  - name_template: ghcr.io/helmwave/gitops:latest
    image_templates:
      - ghcr.io/helmwave/gitops:latest-amd64
      - ghcr.io/helmwave/gitops:latest-arm64v8

  # helmwave: DockerHub
  - name_template: diamon/helmwave:{{ .Version }}
    image_templates:
      - diamon/helmwave:{{ .Version }}-amd64
      - diamon/helmwave:{{ .Version }}-arm64v8
  - name_template: diamon/helmwave:latest
    image_templates:
      - diamon/helmwave:latest-amd64
      - diamon/helmwave:latest-arm64v8
  - name_template: diamon/helmwave:{{ .Version }}-scratch
    image_templates:
      - diamon/helmwave:{{ .Version }}-scratch-amd64
      - diamon/helmwave:{{ .Version }}-scratch-arm64v8
  - name_template: diamon/helmwave:scratch
    image_templates:
      - diamon/helmwave:scratch-amd64
      - diamon/helmwave:scratch-arm64v8


###
# Publishes
###

changelog:
  disable: false
  use: github
  sort: asc

  groups:
    - title: "Tests"
      regexp: "^.*\\(tests?\\):.*$"
      order: 0
    - title: "Dependencies"
      regexp: "^.*\\(deps\\):.*$"
      order: 1
    - title: "CI"
      regexp: "^.*\\(ci\\):.*$"
      order: 2
    - title: "New Features"
      regexp: "^feat(\\(.*\\))?:.*$"
      order: 3
    - title: "Bug Fixes"
      regexp: "^fix(\\(.*\\))?:.*$"
      order: 3
    - title: "Linter"
      regexp: "^.*linter.*$"
      order: 4
    - title: "Other"
      order: 999

  filters:
    exclude:
      - "^WIP:"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - typo
      - "^chore"

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  name_template: "v{{ .Version }}"
  #  draft: true
  prerelease: auto

brews:
  - repository:
      owner: helmwave
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false
    goamd64: v1
    homepage: https://helmwave.app
    description: "Helmwave is true release management for helm"
    license: "MIT"
    directory: Formula
    skip_upload: auto

    custom_block: |
      head "https://github.com/helmwave/helmwave.git", branch: "main"
    test: |
      assert_match version.to_s, shell_output("#{bin/"helmwave"} --version")
    extra_install: |
      generate_completions_from_executable(bin/"helmwave", "completion", shells: [:bash, :zsh])

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

###
# Announces
###

announce:
  telegram:
    enabled: true
    chat_id: -1001484486010
    message_template: |
      Helmwave *{{ replace .Tag "." "\\." }}* is ready\!
      See more: https://github\.com/helmwave/helmwave/releases/tag/{{ replace .Tag "." "\\." }}
