name: Auto assign

on:
  push:
    branches-ignore:
      - "dependabot/*"
  issues:
    types: [opened, reopened]
  pull_request:
    branches-ignore:
      - "dependabot/*"
    types: [opened, reopened]


jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: bubkoo/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.BOT_TOKEN }}

          addAssignees: true
          addReviewers: true
          reviewers: |
            zhilyaev
            r3nic1e
          numberOfReviewers: 1
