name: Changelog

on:
  release:
    types: [ published ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to commit merged changelog
      pull-requests: write # to create PR
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download changie
        run: go install github.com/miniscruff/changie@v1

      - name: Generate release changelog
        run: changie batch $TAG --force
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: .changes/${{ github.event.release.tag_name }}.md

      - name: Update release notes
        env:
          TAG: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh release edit $TAG --notes-file .changes/$TAG.md

      - name: Merge changelog
        run: changie merge

      - name: Create Pull Request for changelog
        uses: peter-evans/create-pull-request@v6
        id: pr
        with:
          add-paths: |
            CHANGELOG.md
            .changes
          commit-message: "chore: update changelog ${{ github.event.release.tag_name }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: "changelog/${{ github.event.release.tag_name }}"
          delete-branch: true
          title: "Changelog/${{ github.event.release.tag_name }}"

      - uses: wow-actions/use-app-token@v2
        id: token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: auto approve and merge
        run: |
          gh pr review --approve ${{ steps.pr.outputs.pull-request-url }}
          gh pr merge --admin --delete-branch --body-file .changes/${{ github.event.release.tag_name }}.md --merge ${{ steps.pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.BOT_TOKEN }}
