name: Dependabot

on:
  pull_request:
    branches: [ main ]
    #    types: [ opened ] uncomment after debug

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.head.ref, 'dependabot/') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch Dependabot metadata
        id: dependabot
        uses: dependabot/fetch-metadata@v2

      - uses: miniscruff/changie-action@v2
        id: changelog
        if: github.actor == 'dependabot[bot]'
        with:
          version: latest
          args: |
            new -k Dependencies -b "${{ github.event.pull_request.title }}" -m Issue=${{ github.event.number }} -m Author=dependabot 

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.actor == 'dependabot[bot]'
        with:
          commit_message: "fix: changie"
      #
      #  dependabot-base:
      #    if: ${{ startsWith(github.event.pull_request.head.ref, 'dependabot/') }}
      #    runs-on: ubuntu-latest
      #    steps:
      - name: get new patch version
        uses: miniscruff/changie-action@v2
        id: version
        with:
          version: latest
          args: next patch

      - id: next
        run: echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
        env:
          TAG: ${{ steps.version.outputs.output }}


      - name: create release branch
        continue-on-error: true
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main
          git checkout -b $BRANCH
          git push origin $BRANCH
        env:
          BRANCH: release/${{ steps.next.outputs.version }}

      - name: change main to release branch
        run: gh pr edit ${{ github.event.number }} -B $BRANCH --remove-reviewer helmwave/maintainers --add-assignee "@me"
        env:
          BRANCH: release/${{ steps.next.outputs.version }}
          GH_TOKEN: ${{ github.token }}

      - name: approve & merge
        run: |
          gh pr review ${{ github.event.number }} -a -c LGTM 
          gh pr merge  ${{ github.event.number }} --auto --merge
        env:
          BRANCH: release/${{ steps.next.outputs.version }}
          GH_TOKEN: ${{ github.token }}

