name: Gif

on:
  pull_request:
    types: [closed]

jobs:
  dogs:
    permissions:
      pull-requests: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Doggoes as an Action
      uses: stanleynguyen/action-dogs@v1
      with:
        github-token: ${{ github.token }}
