name: GitLeaks

on:
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # Only required for Organizations, not personal accounts.
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          
 
