name: GitLeaks
on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  scan:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # Only required for Organizations, not personal accounts.
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          
 
