name: Go lint

on:
  push:
    branches: [ "main", "release/*" ]
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .github/workflows/go-lint.yml
      - .golangci.yml

jobs:
  fix_dublicates:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          skip_after_successful_duplicate: 'true'

  lint:
    if: ${{ needs.fix_dublicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.0
