name: Go Test

on:
  pull_request:
    branches: [ "main", "release/*" ]
    # You can't use yaml anchors here
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - .github/workflows/go-tests.yml

  push:
    branches: [ "main", "release/*" ]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - .github/workflows/go-tests.yml

jobs:
  tests:
    runs-on: ubuntu-latest
    # if: ${{ !startsWith(github.ref_name, 'changelog/') }}
    steps:
      - name: Create KinD cluster
        uses: container-tools/kind-action@v2
        with:
          registry: false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install go modules
        run: go mod download

      - name: Run unit tests
        run: go test -coverprofile=./tests.cov -v -covermode=atomic -timeout=20m --tags=integration ./...

      - name: Run all tests
        run: go test -coverprofile=./tests.cov -v -covermode=atomic -timeout=20m --tags=integration ./...

      - uses: codecov/codecov-action@v4
        with:
          files: ./tests.cov
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
