name: Test GoReleaser config

on:
  pull_request:
    branches: [ "main", "release/*" ]
    paths:
      - ".goreleaser.yml"

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GoReleaser check
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check
