name: JSON Schema

on:
  release:
    types: [ published ]

jobs:
  generate-schema:
    runs-on: ubuntu-latest
    container:
      # I hate gha, Because I can't pass variables to image tag with string manipulation.
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: generate schema
        run: helmwave schema > schema.json

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: schema.json

  upload-schema:
    runs-on: ubuntu-latest
    needs:
      - generate-schema
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: schema.json

      - name: upload to release
        run: gh release upload $TAG schema.json
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
