name: JSON Schema

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      tag:
        description: 'helmwave tag'
        required: true
        type: string

jobs:
  generate-schema-latest:
    if: ${{ github.event_name  == 'release' }}
    runs-on: ubuntu-latest
    container:
      # I hate gha, Because I can't pass variables to image tag with string manipulation.
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: generate schema
        run: helmwave schema > schema.json

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: schema.json

  generate-schema:
    if: ${{ github.event_name  == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    container:
      # I hate gha, Because I can't pass variables to image tag with string manipulation.
      image: ${{ format('ghcr.io/${0}:v${1}', github.repository, github.event.inputs.tag) }}
    steps:
      - name: generate schema
        run: helmwave schema > schema.json

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: schema.json

  upload-schema:
    runs-on: ubuntu-latest
    needs:
      - generate-schema
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: schema.json

      - name: upload to release
        if: ${{ github.event_name  == 'release' }}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
        run: gh release upload $TAG schema.json

      - name: manual upload to release
        if: ${{ github.event_name  == 'workflow_dispatch' }}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.inputs.tag }}
        run: gh release upload $TAG schema.json
  
